version: '3.3'
services:

  # nginx
  nginx:
    image: dbmi/nginx:${nginx_version}
    labels:
      - "edu.hms.harvard.dbmi.stack.name=${STACK_NAME}"
      - "edu.hms.harvard.dbmi.stack.env=${STACK_ENV}"
    restart: always
    # application stack exposed ports
    ports:
      - 80:80
      - 443:443
    networks:
      - public

  ## i2b2transmart stack ##
  # transmart
  transmart:
    image: dbmi/i2b2transmart:${i2b2transmart_version}
    labels:
      - "edu.hms.harvard.dbmi.stack.name=${STACK_NAME}"
      - "edu.hms.harvard.dbmi.stack.env=${STACK_ENV}"
    env_file:
      - ${ENV_FILE}
    environment:
      # debug options
      - JPDA_OPTS="-agentlib:jdwp=transport=dt_socket,address=8000,server=y,suspend=n"
      - JPDA_ADDRESS=8000
      - JPDA_TRANSPORT=dt_socket
      - CATALINA_OPTS=-Xms512m -Xmx2g -Djava.awt.headless=true -XX:+UseConcMarkSweepGC -XX:PermSize=512m -XX:MaxPermSize=512m
    entrypoint: ./bin/catalina.sh jpda run
    restart: always
    depends_on:
      # - db
      - i2b2-wildfly
      - nginx
    networks:
      - public
      - i2b2-hack
    expose:
      - 8080
    ports:
      # debug port
      - 8000:8000
    volumes:
      # local transmart.war directory (for simple development)
      - ${LOCAL_TRANSMART}:/usr/local/tomcat/webapps/:cached
      # required for DI-1026 i2b2-hack localhost fix -Andre
      - ./hosts/nsswitch.conf:/etc/nsswitch.conf:ro


  # i2b2-wildfly
  i2b2-wildfly:
    image: dbmi/i2b2-wildfly:${i2b2_wildfly_version}
    labels:
      - "edu.hms.harvard.dbmi.stack.name=${STACK_NAME}"
      - "edu.hms.harvard.dbmi.stack.env=${STACK_ENV}"
    env_file:
      - ${ENV_FILE}
    restart: always
    # depends_on:
    #   - db
    networks:
      public:
      i2b2-hack:
          aliases:
              - localhost
    expose:
      - 9090
    ports:
      - 9090:9090

  # Rserve
  rserve:
    image: dbmi/rserve:${rserve_version}
    labels:
      - "edu.hms.harvard.dbmi.stack.name=${STACK_NAME}"
      - "edu.hms.harvard.dbmi.stack.env=${STACK_ENV}"
    restart: always
    entrypoint: R CMD
    command: Rserve.dbg --no-save --RS-conf /etc/Rserv.conf
    expose:
      - 6311
    networks:
      - public

networks:
    # for development, keep these unencrypted -Andre
    public:
    i2b2-hack:
