version: '3.3'
services:

  # nginx
  nginx:
    image: dbmi/nginx:${nginx_version}
    labels:
      - "edu.hms.harvard.dbmi.stack.name=${STACK_NAME}"
      - "edu.hms.harvard.dbmi.stack.env=${STACK_ENV}"
    restart: always
    # application stack exposed ports
    ports:
      - 80:80
      - 443:443
    networks:
      - public

  ## i2b2transmart stack ##
  # transmart
  transmart:
    image: dbmi/i2b2transmart:${i2b2transmart_version}
    labels:
      - "edu.hms.harvard.dbmi.stack.name=${STACK_NAME}"
      - "edu.hms.harvard.dbmi.stack.env=${STACK_ENV}"
    env_file:
      - ${ENV_FILE}
    restart: always
    depends_on:
      # - db
      - i2b2-wildfly
      - nginx
    networks:
      - public
      - i2b2-hack
    expose:
      - 8080
    volumes:
      # required for DI-1026 i2b2-hack localhost fix -Andre
      - ./hosts/nsswitch.conf:/etc/nsswitch.conf:ro


  # i2b2-wildfly
  i2b2-wildfly:
    image: dbmi/i2b2-wildfly:${i2b2_wildfly_version}
    labels:
      - "edu.hms.harvard.dbmi.stack.name=${STACK_NAME}"
      - "edu.hms.harvard.dbmi.stack.env=${STACK_ENV}"
    env_file:
      - ${ENV_FILE}
    restart: always
    networks:
      public:
      # DI-1026 i2b2-hack localhost fix -Andre
      i2b2-hack:
          aliases:
              - localhost
    expose:
      - 9090

  # Rserve
  rserve:
    image: dbmi/rserve:${rserve_version}
    labels:
      - "edu.hms.harvard.dbmi.stack.name=${STACK_NAME}"
      - "edu.hms.harvard.dbmi.stack.env=${STACK_ENV}"
    restart: always
    entrypoint: R CMD
    command: Rserve.dbg --no-save --RS-conf /etc/Rserv.conf
    expose:
      - 6311
    networks:
      - public

networks:
    i2b2-hack:
        internal: true
    public:
