version: '3.3'
services:

    i2b2-wildfly:
        image: dbmi/i2b2-wildfly:1.7.09c
        environment:
            - ORACLEHOST=db
            - DB_PORT=1521
            - ORCLDB=ORCLPDB1
        restart: always
        depends_on:
            - db
        networks:
            - public
        ports:
            - 9090:9090
        expose:
            - 9090

    db:
        image: dbmi/i2b2-db:${DB_VERSION}
        networks:
            - public
        expose:
            - 1521



networks:
    public:
