version: '3.3'
services:

    i2b2-schema:
        image: dbmi/i2b2-data:1.7.09
        environment:
            - DB_TYPE=${db_type:-oracle}
            - DB_HOST=db
            - DB_PORT=1521
            - DB_ORASVC=ORCLPDB1
            - DB_USER=pdbadmin
            - DB_PASSWORD=password
        depends_on:
            - db
        networks:
            - public

    transmart-schema:
        image: dbmi/transmart-data:release-18.1-edge
        environment:
            - DB_TYPE=${db_type:-oracle}
            - DB_HOST=db
            - DB_PORT=1521
            - DB_ORASVC=ORCLPDB1
            - DB_USER=pdbadmin
            - DB_PASSWORD=password
        depends_on:
            - db
        networks:
            - public

    db:
        image: dbmi/${db_type:-oracle}:${db_version:-12.2.0.1-ee}
        environment:
            # used to initialize system passwords
            - DB_PASSWORD=password
        networks:
            # public network used to access DB from outside (e.g. SQLDeveloper)
            - public
        volumes:
            - ./startup:/opt/oracle/scripts/startup:ro
        expose:
            - 1521
        ports:
            - 1521:1521



networks:
    public:
