version: '3.3'
services:

    db:
        image: dbmi/i2b2transmart-db:${db_version:-oracle.12.2.0.1-ee-i2b2.1.7.09-tm.release-18.1-v.1.0}
        networks:
            - public
            - private
        expose:
            - 1521
        ports:
            - ${DOCKER_DB_PORT:-1521}:1521


networks:
    public:
    # database exposed on public network makes private network irrelevant
    # useful for local testing with prod.yml -Andre
    private:
        external: true
