version: '3.3'
services:

  # nginx
  nginx:
    image: dbmi/nginx:${nginx_version}
    labels:
      - "edu.hms.harvard.dbmi.stack.name=${STACK_NAME}"
      - "edu.hms.harvard.dbmi.stack.env=${STACK_ENV}"
    restart: always
    # application stack exposed ports
    ports:
      - 80:80
      - 443:443
    networks:
      - public

  ## i2b2transmart stack ##
  # transmart
  transmart:
    image: dbmi/i2b2transmart:${i2b2transmart_version}
    labels:
      - "edu.hms.harvard.dbmi.stack.name=${STACK_NAME}"
      - "edu.hms.harvard.dbmi.stack.env=${STACK_ENV}"
    env_file:
      - ${ENV_FILE}
    restart: always
    depends_on:
      - nginx
      - rserve
      - solr
    networks:
      - public
    volumes:
      - rserve-jobs:/tmp:rw
    expose:
      - 8080

  # Rserve
  rserve:
    image: dbmi/rserve:${rserve_version}
    labels:
      - "edu.hms.harvard.dbmi.stack.name=${STACK_NAME}"
      - "edu.hms.harvard.dbmi.stack.env=${STACK_ENV}"
    restart: always
    networks:
      - public
    expose:
      - 6311
    volumes:
      - rserve-jobs:/tmp:rw

  # solr
  solr:
    image: dbmi/solr:${solr_version}
    labels:
      - "edu.hms.harvard.dbmi.stack.name=${STACK_NAME}"
      - "edu.hms.harvard.dbmi.stack.env=${STACK_ENV}"
    env_file:
      - ${ENV_FILE}
    restart: always
    networks:
      - public
    expose:
      - 8983

volumes:
    # shared volume for R jobs
    rserve-jobs:

networks:
    public:
